# This file defines parameters specific to Gladlaks
#
# When looking at the AUV from above, the thruster placement is:   

# trusters: Used to set parameters in the simulator
initial_conditions:
  auv:
    eta: [0, 0, 0, 0, 0, 0]  # Initial pose  NB! This do not correspond with simulator!

physical:
  mass_kg: 30.9
  center_of_mass: [0, 0, -0.08] # Calculated with respect to the BODY-frame with z axis pointing upwards
  center_of_buoyancy: [0, 0, 0.05]
  inertia: # Inertia about center of mass
    [[ 0.503217, 0.000204, -0.000526],
     [ 0.000204, 0.893449, 0.000038],
     [ -0.000526, 0.000038, 0.919819]]
  water_density: 997
  volume: 0.0295
  length: 0.400
  width: 0.400
  height: 0.200


control_system:
  heading_controller:
    control_bandwidth: 1  # 1/(/thruster/first_order_time_constant*5) ish
    relative_damping_ratio: 1 
    torque_saturation_limit: 22
  depth_controller:
    control_bandwidth: 1  # 1/(/thruster/first_order_time_constant*5) ish
    relative_damping_ratio: 1 
    torque_saturation_limit: 44
  surge_controller:
    control_bandwidth: 1  # 1/(/thruster/first_order_time_constant*5) ish
    relative_damping_ratio: 1 
    torque_saturation_limit: 22
  sway_controller:
    control_bandwidth: 1  # 1/(/thruster/first_order_time_constant*5) ish
    relative_damping_ratio: 1 
    torque_saturation_limit: 22
  frequency: 20

# This simulator is used for providing smooth references for 
# the control system and for obstacle avoidance purposes
auv_simulator:
  w: [0.00001, 0.00001, 0.00001, 100000, 100000, 100000] # Weigths for what dof is prioritised when allocation control forces
  # thrust_gain 0.6 
  # max_linear_velocity


thrusters:
  num: 8
  map: [0, 1, 2, 3, 4, 5, 6, 7]
  first_order_time_constant: 0.2
  rotor_constant: 0.0000035
  duty_cycle_offset: [0, 0, 0, 0, 0, 0, 0, 0]
  duty_cycle_limits: [1200, 1800]

  # Calculated with respect to the BODY-frame with z axis pointing upwards
  positions:
    [[  0.238, -0.220,  0.065],
     [  0.119, -0.220,  0.065],
     [ -0.119, -0.220,  0.065],
     [ -0.240, -0.220,  0.065],
     [ -0.240,  0.220,  0.065],
     [ -0.119,  0.220,  0.065],
     [  0.119,  0.220,  0.065],
     [  0.238,  0.220,  0.065]]
  # Calculated with respect to the BODY-frame with z axis pointing upwards
  orientations:
    [[ 0,      0, -2.356],
     [ 0, -1.571,      0],
     [ 0, -1.571,      0],
     [ 0,      0, -0.785],
     [ 0,      0,  0.785],
     [ 0, -1.571,      0],
     [ 0, -1.571,      0],
     [ 0,      0,  2.356]]
  input_matrix: 
    [[-0.707,  0.000,  0.000,  0.707,  0.707,  0.000,  0.000, -0.707], 
     [-0.707,  0.000,  0.000, -0.707,  0.707,  0.000,  0.000,  0.707],
     [ 0.000,  1.000,  1.000,  0.000,  0.000,  1.000,  1.000,  0.000],
     [ 0.046, -0.220, -0.220,  0.046, -0.046,  0.220,  0.220, -0.046],
     [-0.046, -0.120,  0.120,  0.046,  0.046,  0.119, -0.119, -0.046],
     [-0.324,  0.000,  0.000,  0.325, -0.325,  0.000,  0.000,  0.324]]


# auv_dynamics: Used in the simulator and motion control system
auv_dynamics:
  M_RB: 
    [[ 30.9,    0,    0,    0,    0,    0], 
     [    0, 30.9,    0,    0,    0,    0], 
     [    0,    0, 30.9,    0,    0,    0], 
     [    0,    0,    0, 0.92,    0,    0], 
     [    0,    0,    0,    0, 0.92,    0], 
     [    0,    0,    0,    0,    0, 0.92]]
  M_A: 
    [[ 10.7727, 0, 0, 0, 0, 0], 
     [ 0, 10.7727, 0, 0, 0, 0], 
     [ 0, 0, 49.7679, 0, 0, 0], 
     [ 0, 0, 0, 1.0092, 0, 0], 
     [ 0, 0, 0, 0, 1.0092, 0], 
     [ 0, 0, 0, 0, 0, 0]]
  D: [-9.5909, -9.5909, -50.5595, -13.3040, -13.3040, -5.1559]    # Linear damping
  D_n: [-5.1386, -5.1386, -26.1105, 0, 0, 0]                      # Quadratic damping
 



  
