# This file defines parameters specific to Gladlaks
#
# When looking at the AUV from above, the thruster placement is:   

# trusters: Used to set parameters in the simulator
initial_conditions:
  auv:
    eta: [0, 0, 0, 0, 0, 0]  # Initial pose  NB! This do not correspond with simulator!

physical:
  mass_kg: 30.9
  center_of_mass: [0, 0, -0.08] # Calculated with respect to the BODY-frame with z axis pointing upwards
  center_of_buoyancy: [0, 0, 0.05]
  inertia: # Inertia about center of mass
    [[ 0.503217, 0.000204, -0.000526],
     [ 0.000204, 0.893449, 0.000038],
     [ -0.000526, 0.000038, 0.919819]]
  volume: 0.0325
  length: 0.400
  width: 0.400
  height: 0.200


control_system:
  heading_controller:
    control_bandwidth: 1  # 1/(/thruster/first_order_time_constant*5) ish
    relative_damping_ratio: 1 
    torque_saturation_limit: 22
  depth_controller:
    control_bandwidth: 1  # 1/(/thruster/first_order_time_constant*5) ish
    relative_damping_ratio: 1 
    torque_saturation_limit: 44
  surge_controller:
    control_bandwidth: 1  # 1/(/thruster/first_order_time_constant*5) ish
    relative_damping_ratio: 1 
    torque_saturation_limit: 22
  sway_controller:
    control_bandwidth: 1  # 1/(/thruster/first_order_time_constant*5) ish
    relative_damping_ratio: 1 
    torque_saturation_limit: 22
  controller_frequency: 20


thrusters:
  num: 8
  map: [0, 1, 2, 3, 4, 5, 6, 7]
  first_order_time_constant: 0.2
  rotor_constant: 0.0000035
  # Calculated with respect to the BODY-frame with z axis pointing upwards
  positions:
    [[  0.210,  0.220,  0.040],
     [  0.210, -0.220,  0.040],
     [ -0.105,  0.220,  0.040],
     [ -0.105, -0.220,  0.040],
     [  0.290,  0.220, -0.090],
     [  0.290, -0.220, -0.090],
     [ -0.185,  0.220, -0.090],
     [ -0.185, -0.220, -0.090]]
  # Calculated with respect to the BODY-frame with z axis pointing upwards
  orientations:
    [[ 0,      0, -0.785],
     [ 0,      0,  0.785],
     [ 0,      0,  0.785],
     [ 0,      0, -0.785],
     [ 0,  1.571,      0],
     [ 0,  1.571,      0],
     [ 0,  1.571,      0],
     [ 0,  1.571,      0]]

# auv_dynamics: Used in the simulator and motion control system
auv_dynamics:
  M_RB: 
    [[ 30.9, TODO, TODO, TODO, TODO, TODO], 
     [ TODO, 30.9, TODO, TODO, TODO, TODO], 
     [ TODO, TODO, 30.9, TODO, TODO, TODO], 
     [ TODO, TODO, TODO, TODO, TODO, TODO], 
     [ TODO, TODO, TODO, TODO, TODO, TODO], 
     [ TODO, TODO, TODO, TODO, TODO, 0.919819]]
  M_A: 
    [[ 10.7727, 0, 0, 0, 0, 0], 
     [ 0, 10.7727, 0, 0, 0, 0], 
     [ 0, 0, 49.7679, 0, 0, 0], 
     [ 0, 0, 0, 1.0092, 0, 0], 
     [ 0, 0, 0, 0, 1.0092, 0], 
     [ 0, 0, 0, 0, 0, 0]]
  D: [-9.5909, -9.5909, -50.5595, -13.3040, -13.3040, -1.1559]    # Linear damping
  D_n: [-5.1386, -5.1386, -26.1105, 0, 0, 0]                      # Quadratic damping
 



  
