# This file defines parameters specific to Gladlaks
#
# When looking at the AUV from above, the thruster placement is:   

# trusters: Used to set parameters in the simulator
initial_states:
  eta: [1, 1, 0, 0, 0, 0]  # Initial pose



thrusters:
  num: 8
  map: [0, 1, 2, 3, 4, 5, 6, 7]
  first_order_time_constant: 0.2
  rotor_constant: 0.0000035
  # Calculated with respect to the BODY-frame with z axis pointing upwards
  positions:
    [[  0.210,  0.220,  0.040],
     [  0.210, -0.220,  0.040],
     [ -0.105,  0.220,  0.040],
     [ -0.105, -0.220,  0.040],
     [  0.290,  0.220, -0.090],
     [  0.290, -0.220, -0.090],
     [ -0.185,  0.220, -0.090],
     [ -0.185, -0.220, -0.090]]
  # Calculated with respect to the BODY-frame with z axis pointing upwards
  orientations:
    [[ 0,      0, -0.785],
     [ 0,      0,  0.785],
     [ 0,      0,  0.785],
     [ 0,      0, -0.785],
     [ 0,  1.571,      0],
     [ 0,  1.571,      0],
     [ 0,  1.571,      0],
     [ 0,  1.571,      0]]

# auv_dynamics: Used in the simulator and motion control system
auv_dynamics:
  M_RB: 
    [[ TODO, TODO, TODO, TODO, TODO, TODO], 
     [ TODO, TODO, TODO, TODO, TODO, TODO], 
     [ TODO, TODO, TODO, TODO, TODO, TODO], 
     [ TODO, TODO, TODO, TODO, TODO, TODO], 
     [ TODO, TODO, TODO, TODO, TODO, TODO], 
     [ TODO, TODO, TODO, TODO, TODO, TODO]]
  M_A: 
    [[ 10.7727, 0, 0, 0, 0, 0], 
     [ 0, 10.7727, 0, 0, 0, 0], 
     [ 0, 0, 49.7679, 0, 0, 0], 
     [ 0, 0, 0, 1.0092, 0, 0], 
     [ 0, 0, 0, 0, 1.0092, 0], 
     [ 0, 0, 0, 0, 0, 0]]
  D: [-19.5909, -19.5909, -50.5595, -13.3040, -13.3040, -1.1559]    # Linear damping
  D_n: [-5.1386, -5.1386, -26.1105, 0, 0, 0]                        # Quadratic damping
 


physical:
  mass_kg: 30.9
  # Calculated with respect to the BODY-frame with z axis pointing upwards
  center_of_mass: [0, 0, -0.08]
  center_of_buoyancy: [0, 0, 0.05]
  # Inertia about center of mass
  inertia: 
    [[ 0.503217, 0.000204, -0.000526],
     [ 0.000204, 0.893449, 0.000038],
     [ -0.000526, 0.000038, 0.919819]]
  volume: 0.0325
  length: 0.400
  width: 0.400
  height: 0.200
  displacement_m3: TODO
  drag_coefficients: [TODO, TODO, TODO, TODO, TODO, TODO]
  thruster_layout:
    [[ TODO, TODO, TODO],
     [ TODO, TODO, TODO],
     [ TODO, TODO, TODO],
     [ TODO, TODO, TODO],
     [ TODO, TODO, TODO],
     [ TODO, TODO, TODO],
     [ TODO, TODO, TODO],
     [ TODO, TODO, TODO]]
  thruster_positions:
    [[ TODO, TODO, TODO],
     [ TODO, TODO, TODO],
     [ TODO, TODO, TODO],
     [ TODO, TODO, TODO],
     [ TODO, TODO, TODO],
     [ TODO, TODO, TODO],
     [ TODO, TODO, TODO],
     [ TODO, TODO, TODO]]

propulsion:
  dofs:
    num: 6
    which:
      surge: true
      sway:  true
      heave: true
      roll:  true
      pitch: true
      yaw:   true
  thrusters:
    num: 8
    map: [0, 1, 2, 3, 4, 5, 6, 7]
    direction: [TODO, TODO, TODO, TODO, TODO, TODO, TODO, TODO]
    configuration_matrix:
      [[ TODO, TODO, TODO, TODO, TODO, TODO, TODO, TODO], # Surge
       [ TODO, TODO, TODO, TODO, TODO, TODO, TODO, TODO], # Sway
       [ TODO, TODO, TODO, TODO, TODO, TODO, TODO, TODO], # Heave
       [ TODO, TODO, TODO, TODO, TODO, TODO, TODO, TODO], # Roll
       [ TODO, TODO, TODO, TODO, TODO, TODO, TODO, TODO], # Pitch
       [ TODO, TODO, TODO, TODO, TODO, TODO, TODO, TODO]] # Yaw

    rate_of_change:
      max: TODO # Maximum rate of change in newton per second for a thruster
    characteristics:  # The relationship between thrust in newton and the width in microseconds of the PWM signal to the ESCs
      thrust:      [TODO]
      pulse_width: [TODO]
    offset: [TODO]

  command:
    wrench:
      max:     [ TODO, TODO, TODO, TODO, TODO, TODO]
      scaling: [ TODO, TODO, TODO, TODO, TODO, TODO]

controllers:
  LOS:
    circleOfAcceptance: 0.10
    frequency: 40 # THIS SHOULD BE 40Hz for the controller to perform good. This is because the built in reference model will work 2x faster as if the controller ran at 20Hz
    velocity_gain: 3.5   #0.4
    position_gain: 30.5   #5.0
    attitude_gain: 1.3  #2.5
    integral_gain: 0.024 #0.3
  los_controller:
    PID:
      p: 25.0
      i: 0.0024
      d: 3.5
      sat: 3.0
    backstepping:
      c:  3.75
      k1: 45.0
      k2: 28.0
      k3: 10.5
      
guidance:
  LOS:
    delta: 0.7
        
computer: TODO

torpedos:
  left_pin: TODO
  right_pin: TODO

joystick:
  scaling:
    surge: 10
    sway: 10
    heave: 10
    roll: 5
    pitch: 5
    yaw: 5
